[package]
name = "collections"
version = "0.1.0"
edition = "2021"

[[bin]]
name="traning"
path="./src/traning.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
